# Generated by Django 5.2.4 on 2025-07-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_movie_poster_movie_poster_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
