# Generated by Django 5.2.4 on 2025-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_movie_genres_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
