# Generated by Django 5.2.3 on 2025-07-27 07:05

from django.db import migrations, models
import random
import string

def generate_booking_references(apps, schema_editor):
    Reservation = apps.get_model('reservation', 'Reservation')
    for reservation in Reservation.objects.all():
        reservation.booking_reference = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
        reservation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_qr_code_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='qr_code_path',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.RunPython(generate_booking_references),
        migrations.AlterField(
            model_name='reservation',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
